# data
label_col: target
train_split: 0.15
continous_categories: 100
embeddings_size: 32

# model
n_heads: 8
num_layers: 2

# training
lr: 0.001
batch_size: 32
epochs: 50
steps_per_epoch: 200

# features
categorical:
  - bin_0
  - bin_1
  - bin_2
  - bin_3
  - bin_4
  - nom_0
  - nom_1
  - nom_2
  - nom_3
  - nom_4
  - nom_5
  - nom_6
  - nom_7
  - nom_8
  - nom_9
  - ord_0
  - ord_1
  - ord_2
  - ord_3
  - ord_4
  - ord_5
  - day
  - month

numerical: []
